// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB75bAAyylGMZu2ah7mlRCsjp57ESxKqt0',
    appId: '1:989599461224:android:b39a50ec467d6adfbef0dd',
    messagingSenderId: '989599461224',
    projectId: 'amaliyot-oxiringi-oy',
    storageBucket: 'amaliyot-oxiringi-oy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjZEjxO7aVHaPEH-2zQhja62m9v-RUCaI',
    appId: '1:989599461224:ios:8f87350a9aaf9f1abef0dd',
    messagingSenderId: '989599461224',
    projectId: 'amaliyot-oxiringi-oy',
    storageBucket: 'amaliyot-oxiringi-oy.appspot.com',
    iosClientId: '989599461224-4tqt0okvree81mnbgerccod648sm8dro.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaliyotOxiringiOy',
  );

}